apply plugin: 'com.android.application'

android {
    compileSdkVersion 35
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId "com.chanapps.four.activity"
        minSdkVersion 21
        //noinspection ExpiringTargetSdkVersion
        targetSdkVersion 30
        //before targeting 31+ we need to set flag mutable/immutable to every PendingIntent


        versionCode 100
        versionName "2.0.30"
        multiDexEnabled true
        archivesBaseName = "$applicationId-$versionName" + "-" + getDate()

        //used to get build date info
        buildConfigField "long", "TIMESTAMP", System.currentTimeMillis() + "L"
    }


    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles 'proguard.cfg'
        }
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-DEBUG'
        }

    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    buildFeatures {
        buildConfig true
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt']
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds true
    }
    namespace 'com.chanapps.four.activity'
}

static def getDate() {
    return new Date().format('yyyy.MM.dd.HH.mm.ss')
}

repositories {
    mavenCentral()
}

dependencies {
    api project(':gallery')
    api project(':actionBarPullToRefresh')
    implementation 'com.fasterxml.jackson.core:jackson-core:2.21.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.1'
    implementation 'commons-io:commons-io:2.21.0'
    implementation 'org.apache.commons:commons-lang3:3.20.0'
    implementation 'com.nineoldandroids:library:2.4.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.8.4'

    // debugImplementation because LeakCanary should only run in debug builds.
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'
}
