apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId "com.chanapps.four.activity"
        minSdkVersion 15
        targetSdkVersion 30

        versionCode 100
        versionName "2.0.30"
        multiDexEnabled true
        archivesBaseName = "$applicationId-$versionName"+"-"+getDate()

        //used to get build date info
        buildConfigField "long", "TIMESTAMP", System.currentTimeMillis() + "L"
    }

    lintOptions {
        checkReleaseBuilds true
        abortOnError false
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles 'proguard.cfg'
        }
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-DEBUG'
        }

    }

    packagingOptions {
        resources {
            excludes += ['META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt']
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds true
    }
    namespace 'com.chanapps.four.activity'
}

static def getDate() {
    return new Date().format('yyyy.MM.dd.HH.mm.ss')
}

repositories {
    mavenCentral()
}

dependencies {
    api project(':gallery')
    api project(':actionBarPullToRefresh')
    implementation 'com.fasterxml.jackson.core:jackson-core:2.13.4'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.4'
    implementation 'commons-io:commons-io:2.6'
    implementation 'org.apache.commons:commons-lang3:3.3.1'
    implementation 'com.nineoldandroids:library:2.4.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.8.4'

    // debugImplementation because LeakCanary should only run in debug builds.
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.9.1'

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
}